//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import dayjs from "dayjs";
export class ClientBase {
  public getBaseUrl(url: any, defaultUrl: any) {
    return import.meta.env.VITE_API_URL;
  }
}

export class DrinksClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    getAll(): Promise<DrinkDto[]> {
        let url_ = this.baseUrl + "/api/Drinks/GetAll";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<DrinkDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(DrinkDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DrinkDto[]>(null as any);
    }
}

export class SessionClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    getAll(): Promise<SessionDto[]> {
        let url_ = this.baseUrl + "/api/Session/GetAll";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<SessionDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SessionDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SessionDto[]>(null as any);
    }

    get(sessionId: number): Promise<SessionDto> {
        let url_ = this.baseUrl + "/api/Session/Get?";
        if (sessionId === undefined || sessionId === null)
            throw new Error("The parameter 'sessionId' must be defined and cannot be null.");
        else
            url_ += "sessionId=" + encodeURIComponent("" + sessionId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<SessionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SessionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SessionDto>(null as any);
    }

    newSession(): Promise<number> {
        let url_ = this.baseUrl + "/api/Session/NewSession";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processNewSession(_response);
        });
    }

    protected processNewSession(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    saveDrink(sessionDrinkDto: SessionDrinkDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/Session/SaveDrink";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(sessionDrinkDto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveDrink(_response);
        });
    }

    protected processSaveDrink(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    updateDrink(sessionDrinkDto: SessionDrinkDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/Session/UpdateDrink";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(sessionDrinkDto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateDrink(_response);
        });
    }

    protected processUpdateDrink(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    deleteDrink(sessionDrinkDto: SessionDrinkDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/Session/DeleteDrink";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(sessionDrinkDto);

        let options_: RequestInit = {
            body: content_,
            method: "DELETE",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteDrink(_response);
        });
    }

    protected processDeleteDrink(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class DrinkDto implements IDrinkDto {
    drinkId?: number;
    userId?: number | undefined;
    drinkCategoryId?: number;
    name?: string;
    alcoholPercentage?: number;
    defaultSize?: number;
    imageUrl?: string;
    createdOn?: dayjs.Dayjs;
    createdBy?: string;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string;

    constructor(data?: IDrinkDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.drinkId = _data["drinkId"];
            this.userId = _data["userId"];
            this.drinkCategoryId = _data["drinkCategoryId"];
            this.name = _data["name"];
            this.alcoholPercentage = _data["alcoholPercentage"];
            this.defaultSize = _data["defaultSize"];
            this.imageUrl = _data["imageUrl"];
            this.createdOn = _data["createdOn"] ? dayjs(_data["createdOn"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            this.modifiedOn = _data["modifiedOn"] ? dayjs(_data["modifiedOn"].toString()) : <any>undefined;
            this.modifiedBy = _data["modifiedBy"];
        }
    }

    static fromJS(data: any): DrinkDto {
        data = typeof data === 'object' ? data : {};
        let result = new DrinkDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["drinkId"] = this.drinkId;
        data["userId"] = this.userId;
        data["drinkCategoryId"] = this.drinkCategoryId;
        data["name"] = this.name;
        data["alcoholPercentage"] = this.alcoholPercentage;
        data["defaultSize"] = this.defaultSize;
        data["imageUrl"] = this.imageUrl;
        data["createdOn"] = this.createdOn ? this.createdOn.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        data["modifiedOn"] = this.modifiedOn ? this.modifiedOn.toISOString() : <any>undefined;
        data["modifiedBy"] = this.modifiedBy;
        return data;
    }
}

export interface IDrinkDto {
    drinkId?: number;
    userId?: number | undefined;
    drinkCategoryId?: number;
    name?: string;
    alcoholPercentage?: number;
    defaultSize?: number;
    imageUrl?: string;
    createdOn?: dayjs.Dayjs;
    createdBy?: string;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string;
}

export class SessionDto implements ISessionDto {
    sessionId?: number;
    userId?: number;
    isDeleted?: boolean;
    promile?: number;
    weight?: number;
    sex?: boolean;
    open?: boolean;
    createdOn?: dayjs.Dayjs;
    createdBy?: string;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string;
    sessionDrinks?: SessionDrinkDto[];

    constructor(data?: ISessionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sessionId = _data["sessionId"];
            this.userId = _data["userId"];
            this.isDeleted = _data["isDeleted"];
            this.promile = _data["promile"];
            this.weight = _data["weight"];
            this.sex = _data["sex"];
            this.open = _data["open"];
            this.createdOn = _data["createdOn"] ? dayjs(_data["createdOn"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            this.modifiedOn = _data["modifiedOn"] ? dayjs(_data["modifiedOn"].toString()) : <any>undefined;
            this.modifiedBy = _data["modifiedBy"];
            if (Array.isArray(_data["sessionDrinks"])) {
                this.sessionDrinks = [] as any;
                for (let item of _data["sessionDrinks"])
                    this.sessionDrinks!.push(SessionDrinkDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SessionDto {
        data = typeof data === 'object' ? data : {};
        let result = new SessionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sessionId"] = this.sessionId;
        data["userId"] = this.userId;
        data["isDeleted"] = this.isDeleted;
        data["promile"] = this.promile;
        data["weight"] = this.weight;
        data["sex"] = this.sex;
        data["open"] = this.open;
        data["createdOn"] = this.createdOn ? this.createdOn.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        data["modifiedOn"] = this.modifiedOn ? this.modifiedOn.toISOString() : <any>undefined;
        data["modifiedBy"] = this.modifiedBy;
        if (Array.isArray(this.sessionDrinks)) {
            data["sessionDrinks"] = [];
            for (let item of this.sessionDrinks)
                data["sessionDrinks"].push(item.toJSON());
        }
        return data;
    }
}

export interface ISessionDto {
    sessionId?: number;
    userId?: number;
    isDeleted?: boolean;
    promile?: number;
    weight?: number;
    sex?: boolean;
    open?: boolean;
    createdOn?: dayjs.Dayjs;
    createdBy?: string;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string;
    sessionDrinks?: SessionDrinkDto[];
}

export class SessionDrinkDto implements ISessionDrinkDto {
    sessionDrinkId?: number;
    sessionId?: number;
    drinkId?: number;
    drinkName?: string;
    comment?: string | undefined;
    alcoholPercentage?: number;
    size?: number;
    gramAlcohol?: number;
    alcholRemaining?: number;
    minutesRemaining?: number;
    timeRemaining?: string | undefined;
    createdOn?: dayjs.Dayjs;
    createdBy?: string | undefined;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string | undefined;

    constructor(data?: ISessionDrinkDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sessionDrinkId = _data["sessionDrinkId"];
            this.sessionId = _data["sessionId"];
            this.drinkId = _data["drinkId"];
            this.drinkName = _data["drinkName"];
            this.comment = _data["comment"];
            this.alcoholPercentage = _data["alcoholPercentage"];
            this.size = _data["size"];
            this.gramAlcohol = _data["gramAlcohol"];
            this.alcholRemaining = _data["alcholRemaining"];
            this.minutesRemaining = _data["minutesRemaining"];
            this.timeRemaining = _data["timeRemaining"];
            this.createdOn = _data["createdOn"] ? dayjs(_data["createdOn"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            this.modifiedOn = _data["modifiedOn"] ? dayjs(_data["modifiedOn"].toString()) : <any>undefined;
            this.modifiedBy = _data["modifiedBy"];
        }
    }

    static fromJS(data: any): SessionDrinkDto {
        data = typeof data === 'object' ? data : {};
        let result = new SessionDrinkDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sessionDrinkId"] = this.sessionDrinkId;
        data["sessionId"] = this.sessionId;
        data["drinkId"] = this.drinkId;
        data["drinkName"] = this.drinkName;
        data["comment"] = this.comment;
        data["alcoholPercentage"] = this.alcoholPercentage;
        data["size"] = this.size;
        data["gramAlcohol"] = this.gramAlcohol;
        data["alcholRemaining"] = this.alcholRemaining;
        data["minutesRemaining"] = this.minutesRemaining;
        data["timeRemaining"] = this.timeRemaining;
        data["createdOn"] = this.createdOn ? this.createdOn.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        data["modifiedOn"] = this.modifiedOn ? this.modifiedOn.toISOString() : <any>undefined;
        data["modifiedBy"] = this.modifiedBy;
        return data;
    }
}

export interface ISessionDrinkDto {
    sessionDrinkId?: number;
    sessionId?: number;
    drinkId?: number;
    drinkName?: string;
    comment?: string | undefined;
    alcoholPercentage?: number;
    size?: number;
    gramAlcohol?: number;
    alcholRemaining?: number;
    minutesRemaining?: number;
    timeRemaining?: string | undefined;
    createdOn?: dayjs.Dayjs;
    createdBy?: string | undefined;
    modifiedOn?: dayjs.Dayjs | undefined;
    modifiedBy?: string | undefined;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}