// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDrinkingBuddy.Data.Models
{
    public partial class DrinkCategory
    {
        public DrinkCategory()
        {
            Drink = new HashSet<Drink>();
            InverseDrinkParentCategory = new HashSet<DrinkCategory>();
        }

        public int DrinkCategoryId { get; set; }
        public int? DrinkParentCategoryId { get; set; }
        public string Name { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }

        public virtual DrinkCategory DrinkParentCategory { get; set; }
        public virtual ICollection<Drink> Drink { get; set; }
        public virtual ICollection<DrinkCategory> InverseDrinkParentCategory { get; set; }
    }
}