// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDrinkingBuddy.Data.Models
{
    public partial class Drink
    {
        public Drink()
        {
            SessionDrink = new HashSet<SessionDrink>();
        }

        public int DrinkId { get; set; }
        public int? UserId { get; set; }
        public int DrinkCategoryId { get; set; }
        public string Name { get; set; }
        public double AlcoholPercentage { get; set; }
        public int DefaultSize { get; set; }
        public string ImageUrl { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }

        public virtual DrinkCategory DrinkCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SessionDrink> SessionDrink { get; set; }
    }
}