// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDrinkingBuddy.Data.Models
{
    public partial class User
    {
        public User()
        {
            Drink = new HashSet<Drink>();
            Session = new HashSet<Session>();
        }

        public int UserId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CultureCode { get; set; }
        public double Weight { get; set; }
        public bool Sex { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ICollection<Drink> Drink { get; set; }
        public virtual ICollection<Session> Session { get; set; }
    }
}